### ISSUE TITLE
Instances of page or selected symbols

### ISSUE THREAD

**Issue by sirpooya** [sonburn/symbol-instance-sheet#11]
Hi,
I really love your plugin and it saves me a lot of time.

I just have a suggestion :
It would be great If I could make an Instance Sheet from just a page containing of symbols and not a whole library and if I could choose multiple symbol artboards that I want to make their instances it would be much much better.

thanks alot 👍🙏

**Comment by sonburn** [comment]
@sirpooya Thank you for the feedback and for using my plugin. I think you be pleased with the latest version. Please check it out.
