### ISSUE TITLE
Plugin not running after update

### ISSUE THREAD

**Issue by joergschuster** [sonburn/symbol-instance-sheet#6]
I love this plugin! Unfortunately is stopped converting symbol instances after updating today. It still produces a page but there is nothing on it. I'm using Sketch 50 (54983), Symbol Instance Sheet Version 0.7. Is it only me? Thx for helping me out! 
Joerg

**Comment by sonburn** [comment]
@joergschuster I don't seem to be having issues myself, just verified again this morning by generating 5 new unique sheets from 5 different libraries. Are you experiencing an issue no matter which library you try?

Can you open Utilities > Console.app, find ~/Library/Logs/ in the left window, and select com.bohemiancoding.sketch3 (should appear near or at the top if you have recently opened Sketch). Then back in Sketch, try to run the plugin again, and if there was a failure a log called Plugin Output.log will appear. Would you mind copy/pasting that blob of text here?

**Comment by joergschuster** [comment]
sourceURL: /Users/joergschuster/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Instance Sheet.sketchplugin/Contents/Sketch/script.cocoascript
stack: instanceSheet@/Users/joergschuster/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Instance Sheet.sketchplugin/Contents/Sketch/script.cocoascript:66:28

**Comment by joergschuster** [comment]
Is that the right section?

**Comment by joergschuster** [comment]
Thx for your reply. I tried it again with different libraries. One of them worked fine [iOS UI Design], the other don't, especially not _current document_... 

I copied the Plugin.Output.log after that again:

sourceURL: /Users/joergschuster/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Instance Sheet.sketchplugin/Contents/Sketch/script.cocoascript
stack: instanceSheet@/Users/joergschuster/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Instance Sheet.sketchplugin/Contents/Sketch/script.cocoascript:42:43
sourceURL: /Users/joergschuster/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Instance Sheet.sketchplugin/Contents/Sketch/script.cocoascript
stack: instanceSheet@/Users/joergschuster/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Instance Sheet.sketchplugin/Contents/Sketch/script.cocoascript:66:28

**Comment by sonburn** [comment]
I didn't test current document when I tested earlier (I should have), and it does appear there is a failure...

`TypeError: null is not an object (evaluating 'symbol.symbolMaster')
line: 66
sourceURL: /Users/jbur0001/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Instance Sheet.sketchplugin/Contents/Sketch/script.cocoascript
column: 28
 «Plugin Output»`

That's also a great example of the output I was looking for. The above information lets me know the issue is related to usage of "symbol.symbolMaster" when running Current Document, which makes sense and I should be able to get a fix out shortly.

Thanks for helping me track down the issue. :)

**Comment by sonburn** [comment]
@joergschuster I just published an update (0.8) which should resolve this issue. Please verify!

**Comment by joergschuster** [comment]
Update 0.8 works great. I tried several files with current document instance sheets - all perfectly built.
Thx a lot!

**Comment by sonburn** [comment]
@joergschuster great! Thanks for reporting the issue and helping me troubleshoot, and thanks for using my plugin!
